### ISSUE TITLE
S3 default encryption setting for CloudTrail

### ISSUE THREAD

**Issue by lvthillo** [aws-samples/aws-security-reference-architecture-examples#81]
### The Question

I was checking the CloudTrail, CMK, S3 setup and I saw that the S3 bucket is configured to use the CMK for default encryption.
[Here ](https://github.com/aws-samples/aws-security-reference-architecture-examples/blob/main/aws_sra_examples/solutions/cloudtrail/cloudtrail_org/templates/sra-cloudtrail-org-bucket.yaml#L114)is the code.

```
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref pOrganizationCloudTrailKMSKeyId
              SSEAlgorithm: aws:kms
            BucketKeyEnabled: True
```

Now I was wondering if this was necessary and if it would work?
- Is this configuration necessary? --> CloudTrail encryption is encrypting the objects and uploading them to S3. S3 Default encryption only applies to objects which are uploaded without any encryption information, which is not the case.
-  When you upload an object to s3 without encryption information (if this is even allowed), then the default encryption will be applied, but then the KMS policy should allow that the bucket (in a different account) can use the CMK to encrypt. 

### Environment

- CloudTrail

### Other information

/
